# Generated by Django 4.0.5 on 2022-07-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xohanocy',
            options={'ordering': ['id'], 'verbose_name': 'xohanocy', 'verbose_name_plural': 'xohanocners'},
        ),
        migrations.AddField(
            model_name='tashir_pizza',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.xohanocy'),
        ),
    ]
