# Generated by Django 4.0.5 on 2022-07-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_xohanocy_options_tashir_pizza_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tashir_pizza',
            name='category',
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.xohanocy'),
        ),
        migrations.AddField(
            model_name='salat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.xohanocy'),
        ),
        migrations.AddField(
            model_name='sous',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.xohanocy'),
        ),
    ]
