# Generated by Django 4.0.5 on 2022-07-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_tashir_pizza_category_pizza_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bacpak', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patmutyun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patmutyuny', models.CharField(max_length=50)),
                ('shefxoharar', models.CharField(max_length=50)),
                ('imagexoharar', models.ImageField(blank=True, null=True, upload_to='image')),
                ('imagerestoran', models.ImageField(blank=True, null=True, upload_to='image')),
                ('choreqshabti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choreqshabti_3', to='mainapp.jamer')),
                ('erekshabti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erekshabti_2', to='mainapp.jamer')),
                ('erkushabti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erkushabti_1', to='mainapp.jamer')),
                ('hingshabti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hingshabti_4', to='mainapp.jamer')),
                ('kiraki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kiraki_7', to='mainapp.jamer')),
                ('shabat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shabat_6', to='mainapp.jamer')),
                ('urbat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urbat_5', to='mainapp.jamer')),
            ],
        ),
    ]
