# Generated by Django 4.0.5 on 2022-07-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_jamer_patmutyun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamer',
            name='bacpak',
        ),
    ]
