# Generated by Django 4.0.5 on 2022-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_jamer_bacpak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patmutyun',
            name='patmutyuny',
            field=models.TextField(blank=True),
        ),
    ]
