# Generated by Django 4.0.5 on 2022-07-24 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_patmutyun_patmutyuny'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('people', models.TextField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.TextField(max_length=150)),
            ],
        ),
    ]
