# Generated by Django 4.0.5 on 2022-07-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'Զակասներ'},
        ),
    ]
