# Generated by Django 4.0.5 on 2022-07-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_jamer_options_alter_pizza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patmutyun',
            options={'verbose_name': 'patmutyun', 'verbose_name_plural': 'Պատմությունը'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'social', 'verbose_name_plural': 'Լինկեր'},
        ),
        migrations.AlterModelOptions(
            name='tashir_pizza',
            options={'verbose_name': 'tashir_pizza', 'verbose_name_plural': 'Տաշիր Պիցցա'},
        ),
    ]
