# Generated by Django 4.0.5 on 2022-07-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_patmutyun_options_alter_social_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tashir_pizza',
            options={},
        ),
    ]
