# Generated by Django 4.0.5 on 2022-07-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_tashir_pizza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={},
        ),
    ]
