# Generated by Django 4.0.5 on 2022-07-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_pizza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'Պիցցաներ'},
        ),
    ]
